using CutsceneMaker.Commands;
using CutsceneMaker.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace CutsceneMaker.Compiler;

public static class ContentPackWriter
{
    private const string ContentPatcherFormatVersion = "2.9.0";

    public static void Write(CutsceneData cutscene, string modsPath)
    {
        ArgumentNullException.ThrowIfNull(cutscene);

        if (string.IsNullOrWhiteSpace(modsPath))
        {
            throw new ArgumentException("Mods path is required.", nameof(modsPath));
        }

        string cutsceneName = RequireValue(cutscene.CutsceneName, nameof(cutscene.CutsceneName));
        string outputDirectory = Path.Combine(modsPath, "[CP] " + cutsceneName);
        Directory.CreateDirectory(outputDirectory);

        File.WriteAllText(Path.Combine(outputDirectory, "manifest.json"), BuildManifest(cutscene).ToString(Formatting.Indented));
        File.WriteAllText(Path.Combine(outputDirectory, "content.json"), BuildContent(cutscene).ToString(Formatting.Indented));
    }

    public static JObject BuildManifest(CutsceneData cutscene)
    {
        ArgumentNullException.ThrowIfNull(cutscene);

        string cutsceneName = RequireValue(cutscene.CutsceneName, nameof(cutscene.CutsceneName));
        string uniqueId = RequireValue(cutscene.UniqueId, nameof(cutscene.UniqueId));

        JObject manifest = new()
        {
            ["Name"] = "[CP] " + cutsceneName,
            ["Author"] = "Kree",
            ["Version"] = "1.0.0",
            ["Description"] = "Generated by Cutscene Maker.",
            ["UniqueID"] = "CutsceneMaker." + uniqueId,
            ["UpdateKeys"] = new JArray(),
            ["ContentPackFor"] = new JObject
            {
                ["UniqueID"] = "Pathoschild.ContentPatcher"
            }
        };

        JArray dependencies = BuildDependencies(cutscene);
        if (dependencies.Count > 0)
        {
            manifest["Dependencies"] = dependencies;
        }

        return manifest;
    }

    public static JObject BuildContent(CutsceneData cutscene)
    {
        ArgumentNullException.ThrowIfNull(cutscene);

        return new JObject
        {
            ["Format"] = ContentPatcherFormatVersion,
            ["Changes"] = new JArray
            {
                new JObject
                {
                    ["Action"] = "EditData",
                    ["Target"] = "Data/Events/" + RequireValue(cutscene.LocationName, nameof(cutscene.LocationName)),
                    ["Entries"] = new JObject
                    {
                        [EventKeyBuilder.Build(cutscene)] = EventScriptBuilder.Build(cutscene, ModEntry.Instance.CommandCatalog)
                    }
                }
            }
        };
    }

    private static JArray BuildDependencies(CutsceneData cutscene)
    {
        JArray dependencies = new();
        foreach (string providerModId in cutscene.Commands
            .OfType<EventCommandBlock>()
            .Select(command => command.ProviderModId)
            .Where(id => !string.IsNullOrWhiteSpace(id)
                && !id.Equals("StardewValley", StringComparison.Ordinal)
                && !id.Equals(HelperEventCommandProvider.ModId, StringComparison.Ordinal))
            .Distinct(StringComparer.Ordinal))
        {
            dependencies.Add(new JObject
            {
                ["UniqueID"] = providerModId,
                ["IsRequired"] = true
            });
        }

        return dependencies;
    }

    private static string RequireValue(string? value, string fieldName)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            throw new InvalidOperationException($"{fieldName} is required.");
        }

        return value;
    }
}
